title: Benjamin Byaruhanga
description: Mechatronics & Robotics Student at UCU
remote_theme: pmarsceill/just-the-docs

# Navigation Settings
nav_external_links:
  - title: GitHub
    url: https://github.com/benjaminbyaruhanga2404-maker
